services:
  backend:
    build: .
    ports:
      - "80:80"
    environment:
      - HOST
      - USER
      - PASSWORD
      - DATABASE
      - TOKEN_SECRET
      - REFRESH_TOKEN_SECRET
    env_file:
      - .env
