services:
  backend:
    build: .
    network_mode: "host"
    environment:
      - HOST
      - USER
      - PASSWORD
      - DATABASE
      - TOKEN_SECRET
      - REFRESH_TOKEN_SECRET
    env_file:
      - .env
